name: Run CI Process

on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment (dev, test, stag, prod)'
        required: true
        type: string

jobs:
  ci-process:
    name: CI process
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-ci-process-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup nodeJs
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install yarn
        run: npm install -g yarn

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache Yarn Dependencies
      - uses: actions/cache@v4
        id: yarn-cache
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Check cache
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: echo 'cache not hit'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint Check
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Test
        run: yarn test
